[project]
name = "04-oskari"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "html5lib>=1.1",
    "icecream>=2.1.10",
    "ipykernel>=7.1.0",
    "lxml>=6.0.2",
    "pandas>=3.0.0",
    "pandera[pandas]>=0.29.0",
    "psycopg2>=2.9.11",
    "pytest>=9.0.2",
    "requests>=2.32.5",
    "selenium>=4.40.0",
    "sqlalchemy>=2.0.46",
    "webdriver-manager>=4.0.2",
]
