CREATE TABLE ledger (
    id UUID DEFAULT PRIMARY KEY,
    kunta VARCHAR NOT NULL,
    cardType INTEGER NOT NULL,
    cardid INTEGER NOT NULL,
    accessed_at TIMESTAMP NOT NULL,
    page INTEGER NOT NULL,
    link VARCHAR NOT NULL,
    parsed BOOLEAN NOT NULL
);