# TODO: Add a link health test checks for the scrappers and the structures.
# TODO: Automate the health check as a CI/CD to run everyday.
[Oikotie]
BaseURL = "https://asunnot.oikotie.fi/{category}?pagination={page}&sortBy=published_sort_desc&cardType=101"

[Oikotie.Categories]
[Oikotie.Categories.Vuokra]
Asunnot = "vuokra-asunnot"

[Oikotie.Categories.Myytavat]
asunnot = "myytavat-asunnot"
uudisasunnot = "myytavat-uudisasunnot"

