from typing import Dict, List, Optional

import pandas as pd
import pandera.pandas as pa
from pandera.typing.pandas import Index, DataFrame, Series


class InputSchema(pa.DataFrameModel):
    link: Series[str] = pa.Field(str_length={"max_value": 255})
    accessed_at: Series[pd.Timestamp]

    class Config:
        strict = True


TABLE_COLNAMES: Dict[str, str] = {
    "Hinta": "hinta",
    "Muut maksut": "muut_maksut",
    "Perustiedot": "perustiedot",
    "Talon ja tontin tiedot": "talon_tontin_tiedot",
    "Tekniset tiedot": "tekniikka",
    "Tilat ja materiaalit": "tilat_materiaalit",
    "Valinnainen vuokratontti": "valinnainen_vuokratontti",
}

JSON_COL_DROP = [
    "offers.seller.worksFor.logo",
    "offers.seller.worksFor.url",
    "offers.seller.worksFor.telephone",
    "brand.@type",
    "brand.address",
    "brand.name",
    "brand.logo",
    "brand.url",
    "brand.telephone",
    "itemCondition.@type",
    "geo.@type",
    "offers.@type",
    "address.@type",
    "floorSize.@type",
    "floorSize.unitCode",
    "floorSize.unitText",
    "@context",
    "offers.seller.worksFor.@type",
]
JSON_DATA_COLS = {
    "@type": "property_type",
    "name": "ad_name",
    "url": "url",
    "description": "ad_description",
    "numberOfRooms": "room_count",
    "petsAllowed": "pet_condition",
    "sku": "sku",
    "ProductId": "product_id",
    "floorSize.value": "floor_size",
    "address.addressCountry": "country",
    "address.addressRegion": "region",
    "address.postalCode": "postalcode",
    "address.streetAddress": "street_add",
    "address.addressLocality": "locality",
    "geo.latitude": "latitude",
    "geo.longitude": "latitude",
    "offers.businessFunction": "business_func",
    "offers.price": "price",
    "offers.priceCurrency": "price_currency",
    "offers.seller.name": "seller_name",  # GDPR
    "offers.seller.jobTitle": "seller_job_title",
    "offers.seller.worksFor.address": "seller_co_add",
    "offers.seller.worksFor.name": "seller_co_name",  # GDPR
    "itemCondition.name": "property_condition",
    "identifier": "identifier",
}

META_COL_DROP = [
    "realtorListingNumber",
    "status",
]

META_COLS = {
    "cardId": "cardid",
    "apartmentType": "apartment_type",
    "apartmentTypeId": "appartment_id",
    "size": "size",
    "price": "price",
    "published": "date_published",
    "vertical": "listing_type",
    "subVertical": "listing_subtype",
    "privateListing": "private_listing",
    "brokerName": "broker_name",
    "realtorCompany": "company",
    "realtorCompanyId": "cpmpany_id",
    "realtorCompanyPackage": "company_type",
    "realtorCorporation": "corporation",
    "realtorCorporationId": "corporation_id",
    "zipCode": "postalcode",
    "locationPath": "location_name",
    "habitationType": "property_Type",
    "apartmentBuildYear": "construction_year",
    "listingType": "listing_type",
    "cardViewType": "ad_view_type",
    "extraVisibility": "ad_extra_vis",
}
# TODO: Create a model for the links table. Add the unique ID and duplicate checking validations.


# TODO Create a model for the Meta table + JSON data
TABLES_COLS = {
    "Hinta.Lisätietoa vakuudesta": "lisätietoa_vakuudesta",
    "Hinta.Tuloraja": "tuloraja",
    "Hinta.Vakuus": "vakuus",
    "Hinta.Varallisuusraja": "varallisuusraja",
    "Hinta.Viikkovuokra (alkaen)": "viikkovuokra",
    "Hinta.Vuokra-aika": "Vuokra_aika",
    "Hinta.Vuokra/kk":"Vuokra_kk",
    "Hinta.Vuokrankorotusperusteet": "vuokrankorotusperusteet",
    "Hinta.Vuokrauksen erityisehdot": "vuokrauksen_erityisehdot",
    "Muut maksut.Autopaikan kustannukset":"parking_costs",
    "Muut maksut.Keskimääräinen sähkönkulutus": "avg_elec_consumption",
    "Muut maksut.Lämmityskustannukset":"heating_cost",
    "Muut maksut.Muut kustannukset":"other_costs",
    "Muut maksut.Pysäköintimaksu":"parking_fee",
    "Muut maksut.Rahoitusmuoto":"financing_method",
    "Muut maksut.Saunamaksu":"sauna_fee",
    "Muut maksut.Saunan kustannukset":"sauna_costs",
    "Muut maksut.Sähkömaksu":"elec_fee",
    "Muut maksut.Vesimaksu":"water_fee",
    "Muut maksut.Vesimaksun lisätiedot":"water_fee_info",
    "Perustiedot.Ajo-ohjeet",
    "Perustiedot.Asuinpinta-ala",
    "Perustiedot.Asumistyyppi",
    "Perustiedot.Asunnossa sauna",
    "Perustiedot.Ensiesittelyssä",
    "Perustiedot.Huoneiston kokoonpano",
    "Perustiedot.Huoneita",
    "Perustiedot.Ikkunaremontti",
    "Perustiedot.Ikkunoiden suunta",
    "Perustiedot.Ilmansuunnat",
    "Perustiedot.Julkisivuremontti",
    "Perustiedot.Kattoremontti",
    "Perustiedot.Kaupunginosa",
    "Perustiedot.Keittiö",
    "Perustiedot.Keittiön remontit",
    "Perustiedot.Keittiön varusteet",
    "Perustiedot.Kerroksen lisätiedot",
    "Perustiedot.Kerroksia",
    "Perustiedot.Kerroksien lukumäärä",
    "Perustiedot.Kerros",
    "Perustiedot.Kiinteistötunnus",
    "Perustiedot.Kohdenumero",
    "Perustiedot.Kokonaispinta-ala",
    "Perustiedot.Kotivakuutus edellytetään",
    "Perustiedot.Kunnon lisätiedot",
    "Perustiedot.Kunto",
    "Perustiedot.Kylpyhuoneen remontit",
    "Perustiedot.Kylpyhuoneen varusteet",
    "Perustiedot.Lemmikkieläimet sallittu",
    "Perustiedot.Linkit",
    "Perustiedot.Lisätiedot",
    "Perustiedot.Lisätietoa kalustuksesta",
    "Perustiedot.Lisätietoa lemmikeistä",
    "Perustiedot.Lisätietoa vapautumisesta",
    "Perustiedot.Muut ehdot",
    "Perustiedot.Muut remontit",
    "Perustiedot.Määräaikainen vuokrakohde",
    "Perustiedot.Määräaikaisen vuokran tietoja",
    "Perustiedot.Määräaikaisvuokran loppumispäivä",
    "Perustiedot.Näkymät",
    "Perustiedot.Ominaisuudet",
    "Perustiedot.Osakeluettelo on siirretty huoneistojärjestelmään",
    "Perustiedot.Palvelut",
    "Perustiedot.Parveke",
    "Perustiedot.Parvekeremontti",
    "Perustiedot.Parvekkeen lisätiedot",
    "Perustiedot.Piharemontti",
    "Perustiedot.Pinta-alan lähde",
    "Perustiedot.Pinta-alojen lisätiedot",
    "Perustiedot.Postitoimipaikka",
    "Perustiedot.Putkiremontti",
    "Perustiedot.Rannan (vesistön) tyyppi",
    "Perustiedot.Rannan kuvaus",
    "Perustiedot.Rannan omistus",
    "Perustiedot.Rannan pituus",
    "Perustiedot.Rannan suunta",
    "Perustiedot.Saunan lisätiedot",
    "Perustiedot.Sijainti",
    "Perustiedot.Soveltuvuus liikuntaesteisille",
    "Perustiedot.Säilytystilat",
    "Perustiedot.TV-palvelut",
    "Perustiedot.Tehdyt remontit",
    "Perustiedot.Terassin kuvaus",
    "Perustiedot.Tiedustelut",
    "Perustiedot.Tietoliikennepalvelut",
    "Perustiedot.Tontin pinta-ala",
    "Perustiedot.Tulevat remontit",
    "Perustiedot.Uudiskohteen tila",
    "Perustiedot.Vapautuu",
    "Perustiedot.Varaustilanne",
    "Perustiedot.Vuokralaistyyppi",
    "Perustiedot.Vuokrataan kalustettuna",
    "Talon ja tontin tiedot.Alueen kuvaus",
    "Talon ja tontin tiedot.Energialuokka",
    "Talon ja tontin tiedot.Energiatodistus",
    "Talon ja tontin tiedot.Harrastusmahdollisuudet",
    "Talon ja tontin tiedot.Hissi",
    "Talon ja tontin tiedot.Huoneistojen lukumäärä",
    "Talon ja tontin tiedot.Ilmanvaihto",
    "Talon ja tontin tiedot.Ilmastointijärjestelmä",
    "Talon ja tontin tiedot.Isännöinti",
    "Talon ja tontin tiedot.Kaavoitustiedot",
    "Talon ja tontin tiedot.Kattomateriaali",
    "Talon ja tontin tiedot.Kattotyyppi",
    "Talon ja tontin tiedot.Kerroksia",
    "Talon ja tontin tiedot.Kiinteistön antennijärjestelmä",
    "Talon ja tontin tiedot.Kiinteistön laajakaistayhteys",
    "Talon ja tontin tiedot.Kiinteistönhoito",
    "Talon ja tontin tiedot.Kunnan numero",
    "Talon ja tontin tiedot.Liikehuoneistojen lukumäärä",
    "Talon ja tontin tiedot.Liikenneyhteydet",
    "Talon ja tontin tiedot.Liiketilojen pinta-ala",
    "Talon ja tontin tiedot.Lisätietoa hissistä",
    "Talon ja tontin tiedot.Lisätietoa taloyhtiön saunasta",
    "Talon ja tontin tiedot.Lisätietoa taloyhtiöstä",
    "Talon ja tontin tiedot.Lisätietoja lämmityksestä",
    "Talon ja tontin tiedot.Lisätietoja talosta",
    "Talon ja tontin tiedot.Lämmitys",
    "Talon ja tontin tiedot.Lämmönjakelu",
    "Talon ja tontin tiedot.Maasto",
    "Talon ja tontin tiedot.Muut tilat",
    "Talon ja tontin tiedot.Perustus",
    "Talon ja tontin tiedot.Pihan ilmansuunnat",
    "Talon ja tontin tiedot.Pihan kuvaus",
    "Talon ja tontin tiedot.Rakennuksen käyttöönottovuosi",
    "Talon ja tontin tiedot.Rakennuksen lisätiedot",
    "Talon ja tontin tiedot.Rakennuksen tyyppi",
    "Talon ja tontin tiedot.Rakennusmateriaali",
    "Talon ja tontin tiedot.Rakennusvuoden lisätiedot",
    "Talon ja tontin tiedot.Rakennusvuosi",
    "Talon ja tontin tiedot.Rannan (vesistön) tyyppi",
    "Talon ja tontin tiedot.Rannan kuvaus",
    "Talon ja tontin tiedot.Rungon rakennustapa",
    "Talon ja tontin tiedot.Taloyhtiön nimi",
    "Talon ja tontin tiedot.Taloyhtiössä on sauna",
    "Talon ja tontin tiedot.Tontin koko",
    "Talon ja tontin tiedot.Tontin kuvaus",
    "Talon ja tontin tiedot.Tontin omistus",
    "Talon ja tontin tiedot.Tontin vuokra",
    "Talon ja tontin tiedot.Tontin vuokra päättyy",
    "Talon ja tontin tiedot.Uudiskohde",
    "Talon ja tontin tiedot.Valmistumisaika",
    "Talon ja tontin tiedot.Vesistö",
    "Tekniset tiedot.Puhtaanapito",
    "Tekniset tiedot.Vesi ja jätevesi",
    "Tekniset tiedot.Viemäröinti",
    "Tilat ja materiaalit.Ei kuuluvat varusteet",
    "Tilat ja materiaalit.Keittiön lattia": "kitchen_floor",
    "Tilat ja materiaalit.Keittiön seinä":"kitchen_wall",
    "Tilat ja materiaalit.Kylpyhuoneen lattia":"bathroom_floor",
    "Tilat ja materiaalit.Kylpyhuoneen seinät":"bathroom_wall",
    "Tilat ja materiaalit.Lisätietoja makuuhuoneen varusteista":"bedroom_equipments",
    "Tilat ja materiaalit.Makuuhuoneen lattia":"bedroom_floor",
    "Tilat ja materiaalit.Makuuhuoneen seinät":"bedroom_wall",
    "Tilat ja materiaalit.Muut materiaalit":"other_materials",
    "Tilat ja materiaalit.Muut tilat":"other_spaces",
    "Tilat ja materiaalit.Olohuoneen lattia":"livingroom_floor",
    "Tilat ja materiaalit.Olohuoneen seinät":"livingroom_wall",
    "Tilat ja materiaalit.Olohuoneen varusteet":"livingroom_equipments",
    "Tilat ja materiaalit.Ominaisuudet":"properties",
    "Tilat ja materiaalit.Pintamateriaalit":"surface_material",
    "Tilat ja materiaalit.Pysäköintitilan kuvaus":"",
    "Tilat ja materiaalit.Pysäköintitilan lämmitys",
    "Tilat ja materiaalit.Pysäköintitilan sähköpistoke",
    "Tilat ja materiaalit.Yhteiset tilat",
}
