from bs4 import BeautifulSoup
from typing import Dict, List, Any
# The add overview is like this: class="listing-overview"
# the containers for each table is: "class="listing-details""
# get the table title
# get each row information


def get_meta_data(soup: BeautifulSoup) -> Dict[str, Any]:
    """extract metadata tages.
    This function extract the metadata tags data, formated this way: <meta property=og:*>
    The extracted data contains an overview of the add, as well as it location which is crucial for post processing of the data.


    Parameters
    ----------
    soup : BeautifulSoup
        The bs4 object created from the html file

    Returns
    -------
    Dict[str,Any]
        A dictionary with the metadata as nested dict.
    """
    pass


def get_script_json_data(soup: BeautifulSoup) -> Dict[str, Any]:
    """Extract script tags with type=application/ld+json

    These script tags contain information sent for the database. They contain some information that is not available in the metadata nor the ad tables.

    Parameters
    ----------
    soup : BeautifulSoup
        The bs4 object created from the html file

    Returns
    -------
    Dict[str,Any]
        A dictionary with the data as nested dict.
    """
    pass


def get_script_meta_data(soup: BeautifulSoup) -> Dict[str, Any]:
    """Extract script with `var otAsunnot` contents.
    This script extract and parse the json data nested as js script.
    The information is the clean version of most of the data obtained from the database.


    Parameters
    ----------
    soup : BeautifulSoup
        The bs4 object created from the html file

    Returns
    -------
    Dict[str,Any]
        A dictionary with the data as nested dict.
    """
    pass


def get_table_htmls_sections(soup: BeautifulSoup) -> Dict[str, BeautifulSoup]:
    """Extract innerHTML tables.
    There are inner html objects that contain the tables.
    Each table has a header. The header is set as the key, and the inner HTML table bs4 object is the value.

    Parameters
    ----------
    soup : BeautifulSoup
        The bs4 object created from the html file

    Returns
    -------
    Dict[str, BeautifulSoup]
        A dictionary with table name as key and bs4 inner html object as value.
    """
    pass


def generate_table_from_html(soup: BeautifulSoup) -> Dict[str, Any]:
    """Clean HTML table
    This script converts the inner HTML bs4 object into a clean json file containing the information of the table.
    The table is generated by processing the <dd> and <dt> tags.

    Parameters
    ----------
    soup : BeautifulSoup
        innerHTML b4 objetc containing a table.

    Returns
    -------
    Dict[str, Any]
        a dictionary of the table.
    """

    pass


def compile_record_json(data_dicts):
    pass





